################################################################################################################################################
# Project: Dependent Applications
# Date: 03-11-2013
# By: Peter van der Woude
# Version: 0.9 Public
# Usage: PowerShell.exe -ExecutionPolicy ByPass .\Show-DependentApplications.ps1 -ApplicationName <ApplicationName> -SiteCode <SiteCode> -SiteServer <SiteServer>
################################################################################################################################################
[CmdletBinding()]

param (
[string]$ApplicationName,
[string]$SiteCode,
[string]$SiteServer,
[string]$ApplicationVersion = "Show Dependent Applications v0.9p"
)

function Get-DependentApplications {
    $WorkArray = New-Object System.Collections.ArrayList
    $SortArray = New-Object System.Collections.ArrayList
    $DataArray = New-Object System.Collections.ArrayList
    $ApplicationCIID = (Get-WmiObject -Class SMS_ApplicationLatest -Namespace root/SMS/site_$($SiteCode) -ComputerName $SiteServer -Filter "LocalizedDisplayName='$ApplicationName'").CI_ID
    $DependentApplications = Get-WmiObject -Class SMS_AppDependenceRelation -Namespace root/SMS/site_$($SiteCode) -ComputerName $SiteServer -Filter "ToApplicationCIID='$ApplicationCIID'"
    foreach ($DependentApplication in $DependentApplications) {
        $FromApplicationCIIDs = $DependentApplication.FromApplicationCIID
        foreach ($FromApplicationCIID in $FromApplicationCIIDs) {
            $FromApplicationName = Get-ApplicationName($FromApplicationCIID)
            if ($FromApplicationName -ne $Null) {
                $FromDeploymentTypeCIIDs = $DependentApplication.FromDeploymentTypeCIID
                foreach ($FromDeploymentTypeCIID in $FromDeploymentTypeCIIDs) {
                    $FromDeploymentTypeName = Get-DeploymentTypeName($FromDeploymentTypeCIID)
                }
                $ToDeploymentTypeCIIDs = $DependentApplication.ToDeploymentTypeCIID
                foreach ($ToDeploymentTypeCIID in $ToDeploymentTypeCIIDs) {
                    $ToDeploymentTypeName = Get-DeploymentTypeName($ToDeploymentTypeCIID)
                }
                $WorkHash = [ordered] @{
                    "From Application"=$FromApplicationName; 
                    "From DeploymentType"=$FromDeploymentTypeName; 
                    "To Application"=$ApplicationName;
                    "To DeploymentType"=$ToDeploymentTypeName
                }
                $WorkObject = New-Object PSObject -Property $WorkHash
                $WorkArray.Add($WorkObject)
            }
        }
    }
    $SortArray = $WorkArray | Sort-Object "From Application"
    foreach($Item in $SortArray) {
        $DataArray.Add($Item)
    }
    $dataGridView1.DataSource = $DataArray
    for ($i=0; $i -lt $dataGridView1.ColumnCount; $i++) {
	    $dataGridView1.Columns[$i].width = 175
    }
    $form1.refresh()
}

Function Get-ApplicationName {
    param (
    [string]$ApplicationCIID
    )
    $ApplicationName = (Get-WmiObject -Class SMS_ApplicationLatest -Namespace root/SMS/site_$($SiteCode) -ComputerName $SiteServer -Filter "CI_ID='$ApplicationCIID'").LocalizedDisplayName
    Return $ApplicationName
}

Function Get-DeploymentTypeName {
    param (
    [string]$DeploymentTypeCIID
    )
    $DeploymentTypeName = (Get-WmiObject -Class SMS_DeploymentType -Namespace root/SMS/site_$($SiteCode) -ComputerName $SiteServer -Filter "CI_ID='$DeploymentTypeCIID'").LocalizedDisplayName
    Return $DeploymentTypeName
}

#Generated Form Function
function GenerateForm {
    ########################################################################
    # Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
    # Generated On: 29-5-2013 20:26
    # Generated By: Peter
    ########################################################################

    [reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
    [reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null

    $form1 = New-Object System.Windows.Forms.Form
    $dataGridView1 = New-Object System.Windows.Forms.DataGridView
    $button1 = New-Object System.Windows.Forms.Button
    $label1 = New-Object System.Windows.Forms.Label
    $label2 = New-Object System.Windows.Forms.Label
    $label3 = New-Object System.Windows.Forms.Label
    $label4 = New-Object System.Windows.Forms.Label
    $linkLabel1 = New-Object System.Windows.Forms.LinkLabel
    $linkLabel2 = New-Object System.Windows.Forms.LinkLabel
    $InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState

    $button1_OnClick= {
	    $form1.Close()
    }
    
    $linkLabel1_OpenLink= {
        [system.Diagnostics.Process]::start($linkLabel1.text)
    }

    $linkLabel2_OpenLink= {
        [system.Diagnostics.Process]::start("http://twitter.com/pvanderwoude")
    }

    $OnLoadForm_UpdateGrid= {
       Get-DependentApplications
    }

    #Create form1
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 408
    $System_Drawing_Size.Width = 499
    $form1.ClientSize = $System_Drawing_Size
    $form1.DataBindings.DefaultDataSourceUpdateMode = 0
    $form1.Name = "form1"
    $form1.Text = "$ApplicationVersion - P.T. van der Woude"

    #Create dataGridView1
    $dataGridView1.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 13
    $System_Drawing_Point.Y = 40
    $dataGridView1.Location = $System_Drawing_Point
    $dataGridView1.Name = "dataGridView1"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 305
    $System_Drawing_Size.Width = 473
    $dataGridView1.ReadOnly = $True
    $dataGridView1.SelectionMode = 'FullRowSelect'
    $dataGridView1.Size = $System_Drawing_Size
    $dataGridView1.TabIndex = 2
    $form1.Controls.Add($dataGridView1)

    #Create button1
    $button1.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 337
    $System_Drawing_Point.Y = 353
    $button1.Location = $System_Drawing_Point
    $button1.Name = "button1"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 150
    $button1.Size = $System_Drawing_Size
    $button1.TabIndex = 1
    $button1.Text = "Close"
    $button1.UseVisualStyleBackColor = $True
    $button1.add_Click($button1_OnClick)
    $form1.Controls.Add($button1)
    
    #Create label1
    $label1.DataBindings.DefaultDataSourceUpdateMode = 0
    $label1.Font = New-Object System.Drawing.Font("Tahoma",14.25,0,3,0)
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 13
    $System_Drawing_Point.Y = 13
    $label1.Location = $System_Drawing_Point
    $label1.Name = "label1"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 225
    $label1.Size = $System_Drawing_Size
    $label1.TabIndex = 0
    $label1.Text = "Dependent Applications"
    $form1.Controls.Add($label1)

    #Create label2
    $label2.DataBindings.DefaultDataSourceUpdateMode = 0
    $label2.Font = New-Object System.Drawing.Font("Tahoma",8.25,0,3,0)
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 260
    $System_Drawing_Point.Y = 19
    $label2.Location = $System_Drawing_Point
    $label2.Name = "label2"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 254
    $label2.Size = $System_Drawing_Size
    $label2.TabIndex = 0
    $label2.Text = "- Including their specific deployment types -"
    $form1.Controls.Add($label2)

    #Create label3
    $label3.DataBindings.DefaultDataSourceUpdateMode = 0
    $label3.Font = New-Object System.Drawing.Font("Tahoma",8.25,0,3,0)
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 12
    $System_Drawing_Point.Y = 382
    $label3.Location = $System_Drawing_Point
    $label3.Name = "label3"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 48
    $label3.Size = $System_Drawing_Size
    $label3.TabIndex = 1
    $label3.Text = "My blog:"
    $form1.Controls.Add($label3)
        
    #Create label4
    $label4.DataBindings.DefaultDataSourceUpdateMode = 0
    $label4.Font = New-Object System.Drawing.Font("Tahoma",8.25,0,3,0)
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 286
    $System_Drawing_Point.Y = 382
    $label4.Location = $System_Drawing_Point
    $label4.Name = "label4"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 117
    $label4.Size = $System_Drawing_Size
    $label4.TabIndex = 2
    $label4.Text = "Follow me on twitter:"
    $form1.Controls.Add($label4)

    #Create linkLabel1
    $linkLabel1.DataBindings.DefaultDataSourceUpdateMode = 0
    $linkLabel1.Font = New-Object System.Drawing.Font("Tahoma",8.25,0,3,0)
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 63
    $System_Drawing_Point.Y = 382
    $linkLabel1.Location = $System_Drawing_Point
    $linkLabel1.Name = "linkLabel1"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 142
    $linkLabel1.Size = $System_Drawing_Size
    $linkLabel1.TabIndex = 0
    $linkLabel1.TabStop = $True
    $linkLabel1.Text = "www.petervanderwoude.nl"
    $linkLabel1.add_click($linkLabel1_OpenLink)
    $form1.Controls.Add($linkLabel1)

    #Create linkLabel2
    $linkLabel2.DataBindings.DefaultDataSourceUpdateMode = 0
    $linkLabel2.Font = New-Object System.Drawing.Font("Tahoma",8.25,0,3,0)
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 400
    $System_Drawing_Point.Y = 382
    $linkLabel2.Location = $System_Drawing_Point
    $linkLabel2.Name = "linkLabel2"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 90
    $linkLabel2.Size = $System_Drawing_Size
    $linkLabel2.TabIndex = 3
    $linkLabel2.TabStop = $True
    $linkLabel2.Text = "@pvanderwoude"
    $linkLabel1.add_click($linkLabel2_OpenLink)
    $form1.Controls.Add($linkLabel2)

    $InitialFormWindowState = $form1.WindowState

    $form1.add_Load($OnLoadForm_UpdateGrid)
    $form1.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
